# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fegoland
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Il est question ici de notes de lecture, idées, bref, de tout et de rien. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fego.github.io/" # the base hostname & protocol for your site
github_username:  fego

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal